### ISSUE TITLE
Coroutines support.

### ISSUE THREAD

**Issue by proofit404** [dry-python/stories#12]

**Comment by thedrow** [comment]
I've been browsing the code for a bit and I can't wrap my head around this yet.
I really need this for Celery.

**Comment by proofit404** [comment]
Hi,

To support coroutines we should do a few things.

1. Write async function similar to this: https://github.com/dry-python/stories/blob/fb7aa246183eb844023c7c1de984de7482698e72/src/stories/_exec/function.py#L6

2. Method list should be something more than a list https://github.com/dry-python/stories/blob/fb7aa246183eb844023c7c1de984de7482698e72/src/stories/_wrap.py#L12 Wrap function should check each method and detect coroutines. If there is at least one coroutine in the method list we should wrap regular functions in the async callables.

3. After that, we should use this execute function and method list together in the call and run methods https://github.com/dry-python/stories/blob/fb7aa246183eb844023c7c1de984de7482698e72/src/stories/_mounted.py#L46 I guess we can use an object with `__await__` method.

@supadrupa is interested in this feature too. Maybe we all can collaborate to implement it. I promise to finish in-progress features quickly and roll out a new release.

Regards, Artem.

**Comment by thedrow** [comment]
I'd love to collaborate on this.

**Comment by proofit404** [comment]
First of all, we should adopt `tests/test_base_async.py` from `tests/test_base.py`. This should be a copy-pasted module with async await properly set. `pytest-asyncio` can be used to run them. This tests should be skipped on python 2.

**Comment by proofit404** [comment]
There is some work going on to implement this: https://github.com/supadrupa/stories/commit/17aee222da4b9b66bdaaa15ef492cb21c77d0491
