### ISSUE TITLE
Use returns as a result

### ISSUE THREAD

**Issue by thedrow** [dry-python/stories#124]
The [returns](https://github.com/dry-python/returns) library was created for usage in dry-python I'm assuming.
We should replace our `stories._return` module with it.

**Comment by proofit404** [comment]
Hi,
Yes, `returns` is a lightweight alternative to the stories library with a slightly different approach.
I still trying to wrap my head around this integration.
Maybe @sobolevn has some insights on it.
Regards, Artem.

**Comment by sobolevn** [comment]
I had some ideas on how to integrate them together, but typing did not work well.
So, I am open to any suggestions.

**Comment by proofit404** [comment]
I guess the main goal for us - use `@pipeline` decorator on each step. So we need to integrate context object with it. `@safe` will be used on the implementation of each step in separate modules.

**Comment by proofit404** [comment]
Not a the moment I guess.

The more I'm thinking about rollbacks implementation, the more I start to realize it'll be incompatible at all.

I guess we should keep `stories` and `returns` as a separate implementation of the same ideas with a different approach.
