### ISSUE TITLE
[Documentation] PNG files are not rendered in the documentation 

### ISSUE THREAD

**Issue by fbjorn** [dry-python/stories#145]
Looks like static images are served improperly:
![image](https://user-images.githubusercontent.com/9670990/60183998-f7376b80-982f-11e9-94e8-f28d65950086.png)

https://stories.readthedocs.io/en/latest/why/
https://stories.readthedocs.io/static/pytest.png
https://stories.readthedocs.io/static/method-flowchart.png

**Comment by proofit404** [comment]
Thanks for the report!

Fixed by 5400ee089d572880b75c420c790b6fbe430e842b.
