### ISSUE TITLE
Unit testing a story method

### ISSUE THREAD

**Issue by M0dM** [dry-python/stories#252]
Hi,

I am trying to unit test each method (step) in a story with fake context data (using python3 SimpleNamespace from types).
I could not figured out how to do it yet...

Could you please write a two line documentation to explain how to do so.

Regards,
M0dM

**Comment by M0dM** [comment]
Forget this, It is just working fine.
My story method implementation had not argument...

**Comment by proofit404** [comment]
Hi, thanks for letting me know about this approach.

I prefer to test the behavior of the story at once. If you don't write an actual implementation of the step inside the story, it became a lot easier. Story steps are a kind of private methods.

I prefer to use the [Delegate implementation](https://stories.readthedocs.io/en/latest/composition/#delegate-implementation) approach. That way you can unit test an actual implementation of the story step without a story at all.

I hope that helps.

Best regards,
Artem.
