### ISSUE TITLE
Possibly bug in contract creation

### ISSUE THREAD

**Issue by gtors** [dry-python/stories#277]
py: 3.8
stories: 0.10.2

https://github.com/dry-python/stories/blob/75954a70b13c092281571b1da510de0d40ec9d3c/src/_stories/contract.py#L207-L212

Seems `isinstance` cannot be applied here because `spec` is a type/class. Maybe  you mean  `issubclass` ?

**Comment by gtors** [comment]
`combine_contract` also broken, because `isinstance` cannot be applied to `parent.origin` and `child.origin` (origin it's a class)
https://github.com/dry-python/stories/blob/75954a70b13c092281571b1da510de0d40ec9d3c/src/_stories/contract.py#L524-L531

**Comment by gtors** [comment]
:man_facepalming:  I didn't take it into account that PydanticSpec is metaclass

**Comment by proofit404** [comment]
Yeh, it's a complicated package :slightly_smiling_face:
