### ISSUE TITLE
Parallelize tests to shorten CI runtime.

### ISSUE THREAD

**Issue by thedrow** [dry-python/stories#292]
The number of tests we have is growing.
In fact #289 doubled the number of tests we execute.

We should use pytest-xdist to parallelize the running of the tests in CI.
Unfortunately coverage measurement doesn't work correctly even if I use pytest-cov.
See #290.

We need to figure out the problem and fix it.

**Comment by proofit404** [comment]
I don't think we'll do this research in the nearest future.

If CI time will be an issue for us at some point, we will return to this issue.

Fill free to reopen.
