### ISSUE TITLE
Parameterized steps

### ISSUE THREAD

**Issue by thedrow** [dry-python/stories#344]
Sometimes you have steps which repeat themselves but have constant arguments that can be determined during story definition.

For example a step which uploads a file to an S3 bucket can be parameterized by the S3 bucket it should be uploading to.
The alternative would be to create a step which simply sets the context to a constant before the execution of the upload step.
This is verbose and frankly unnecessary.

Suggested syntax:
```python
class Foo:
  @story
  @arguments("file")
  def do(I):
    I.upload_to_s3.partial(bucket_name='special_files')

  def upload_to_s3(self, ctx, bucket_name='default'):
    pass
```

**Comment by proofit404** [comment]
Why not make it an argument of the story?
```python
class Action:
    @story
    @arguments('file', 'bucket')
    def do(I):
        I.upload_to_s3

    def upload_to_s3(self, ctx):
        boto.upload(ctx.bucket, ctx.file)
        return Success()
```
If the bucket name should be configured application vide, it's also possible to create a wrapper around the boto library and use `dependencies` to pass it to every story it needed.
```python
@attrs
class Action:
    @story
    @arguments('file')
    def do(I):
        I.upload_to_s3

    def upload_to_s3(self, ctx):
        self.uploader(ctx.file)
        return Success()

    uploader = attrib()


@attrs
class Uploader:
    bucket = attrib()
    def __call__(self, file):
        boto.upload(self.bucket, file)


Action(Uploader('default')).do('the_file.txt')
```
From my experience, the business logic itself should not be aware of configuration details like this. It's even better to change `upload_to_s3` to something like `save_the_file`.

What worries me in the semantic you propose is something similar to the props drilling problem in react. If I want to override the value in a substory of the substory of the substory of the substory of the story I'm using, every story in that chain should know about this step param.

**Comment by thedrow** [comment]
I think you're missing the point.
The point is that sometimes you have common behavior which is fixed at story definition time.
Let me give you another example which is what I'm currently facing with:
You have a state machine with different states A, B & C.
Each story invokes a transition to a fixed state. That fact **never** changes.

We could do the following:
```python
class MyStateMachine(StateMachine):
  def __init__(self):
    self.change_state_to_A = functools.partial(self.change_state, 'A')
    # ...

  @story
  def do_A(I):
    I.before_A1
    I.before_A2
    I.change_state_to_A
    I.after_A1
    I.after_A2

  # ...
```

My proposal is to introduce a sugar syntax for that usecase alone.

**Comment by proofit404** [comment]
> That fact never changes.

Why not hard code that state in the step definition then?

```python
def change_state_to_A(self, ctx):
    self.change_state('A', **kwargs)
    return Success()
```
It's way easier and straightforward. Yes, your approach will save us a few words to type. But the maintenance cost will be bigger than the benefit we gain.

**Comment by thedrow** [comment]
Because sugar is what makes open source libraries so sweet.

Seriously though, typing less is always an objective when creating libraries.

**Comment by proofit404** [comment]
The purpose of our DSL is an explanation of the business process in mostly human language. Coupling values to it is a mistake in my opinion. There is a lot of places where we could put constants in Python.  Making story spec one of them isn't what I want.
