### ISSUE TITLE
Using partial functions in async stories incorrectly raises a StoryDefinitionError

### ISSUE THREAD

**Issue by thedrow** [dry-python/stories#348]
As a followup to #347, even if I do set a `__name__` to the partial function it is not correctly detected as async.
Since this problem [was fixed](https://bugs.python.org/issue33261) in Python 3.8 that's no longer the case but we do support older Python 3 versions as well so we should backport this check.

**Comment by thedrow** [comment]
Note that this is still a problem with `partialmethod` even after Python 3.8.
See [issue](https://bugs.python.org/issue38364) and the PR at https://github.com/python/cpython/pull/16600.

**Comment by proofit404** [comment]
Superseded by #349
