### ISSUE TITLE
@story should support functions, not only methods.

### ISSUE THREAD

**Issue by proofit404** [dry-python/stories#86]
- [ ] Story class should be more user-friendly.
- [ ] Replace `StoryWrapper` with `BoundStory`.
- [ ] Add public method for attaching a story to the object (`bind` or `mount`).
- [ ] **Maybe** add `from_list` method to create `BoundStory` at once.
- [ ] Replace descriptor with `from_function` method.

**Comment by proofit404** [comment]
#### This helps to support sync and async steps simultaneously.

**Comment by sobolevn** [comment]
@proofit404 do you have any kind of API for this in mind? I would love to have a look at it.

**Comment by proofit404** [comment]
I think about something like this:

```python
@story 
@arguments('one', 'two', 'three')
def buy_subscription(I):
    I.create_order
    I.calculate_price
    I.request_payment
    I.notify_user

async def create_order(ctx):
    pass

async def calculate_price(ctx):
    pass

buy = buy_subscription.mount([
    create_order,
    calculate_price,
    ...,
])

order_id = await buy(1, 2, 3)
# or
result = await buy.run(1, 2, 3)
order_id = result.value
```
We can reuse same story with synchronous implementation
```python
def create_order(ctx):
    pass

def calculate_price(ctx):
    pass

buy = buy_subscription.mount([
    create_order,
    calculate_price,
    ...,
])

order_id = buy(1, 2, 3)
# or
result = buy.run(1, 2, 3)
order_id = result.value
```

**Comment by proofit404** [comment]
We will keep the API consistent and class-based only for now.
