### ISSUE TITLE
Class-based API

### ISSUE THREAD

**Issue by sobolevn** [dry-python/stories#96]
To continue our research/discussion about class-based APIs.
Related: #86

Goals:
- Make current API more familiar for `python` users
- Make it impossible to use any logic inside steps definition at the same time

Non-goals:
- We should not make it familiar for `ruby` users

## Current state

What we currently have?

```python
@story 
def do(I):
    I.foo
    I.bar
    I.baz
```

That it working and working pretty great, but there are some things to address:
1. It is still possible to put logics inside this story definition like in this example:

```python
from flask import request

@story 
def do(I):
    I.foo
    I.bar
    if request.user:
        I.baz
```

2. It makes some `python` users uncomfortable, since we are not used to statement-based APIs. It might be a serious problem for wide adoption of the project

## Proposal

We can have a look at several options to define APIs the way it won't violate these two criteria.

### Class attribute

```python
@story
class OrderSubmission(object):
     steps = [
          _checkout,
          _user_notification,
          _crm_webhook,
     ]

    def __init__(self, email_sender: EmailSender, webhook_sender: WebhookSender) -> None:
          # Dependencies to be injected
          ...

     def _checkout(self, context: Context[OrderDomain]) -> Monad:
            ...

     def _user_notification(self, context: Context[OrderDomain]) -> Monad:
           if not context.user:
                  return Skip('User is not registered')
           ...

     def _crm_webhook(self, context: Context[OrderDomain]) -> Monad:
           ...
```

This is a very early draft. It is not proposed as a final solution. Just as a entrypoint to discussion. 

Opened questions:
- [ ] How to define step arguments in function definition, I am talking about `context` argument. What type should it be?
- [x] How to define return type of the step? There are a lot of edge cases for `Error`, `Skip`, etc
- [ ] Substories (#76 ) are not covered at all
- [ ] Should we follow the same unified interface as `ruby` does: `__init__` and `__call__`? I like it!
- [x] Notice the raw `object` in parents list, is it fine?
- [ ] Notice that all steps are protected. Should it be this way? I think that it should be enforced

**Comment by proofit404** [comment]
Hi,

Many people ask what will happen if someone put `if` statement in the story definition.

In my opinion, linter is the only variant which will protect us from this violation.

For example, 

```python
from flask import request

@story
class OrderSubmission(object):
     steps = [
          _checkout,
          _user_notification,
          _crm_webhook if request.current_user else _anonymous_webhook,
     ]
```

**Comment by proofit404** [comment]
Also, I want to point a few requirements for this DSL design.

### Definition of the substory should be easy

Current state:

```python
# using inheritance
class Action:
    @story 
    def do(I):
        I.prepare
        I.do_something
        I.finish

    @story 
    def do_something(I):
        I.do_some
        I.do_thing
```
```python
# using dependency injection
class Action:
    @story 
    def do(I):
        I.prepare
        I.do_something
        I.finish

    def __init__(self, do_something):
         self.do_something = do_something

class SubAction:
    @story 
    def do_something(I):
        I.do_some
        I.do_thing
```

**Comment by proofit404** [comment]
### Definition of the rollback steps should be easy

[Current plan](https://github.com/dry-python/stories/issues/88):

```python
class Action:
    @story 
    def do(I):
        with I.create_transaction:
            ~I.rollback_transaction
            ~I.flush_cache
```
This way we can define a few steps to rollback another step.

**Comment by proofit404** [comment]
### Definition of substory conditionals should be easy

[Current plan](https://github.com/dry-python/stories/issues/76):

```python
class Action;
    @story 
    def do(I):
        I.check_balance
        Compare('can_purchase') & I.perform_purchase | I.show_error

    @story 
    def perform_purchase(I):
        ...

    @story 
    def show_error(I):
        ...

**Comment by proofit404** [comment]
I think the raw object in the parent list is fine. Maybe we should use inheritance from the `Story` class instead of `@story` decorator.

**Comment by proofit404** [comment]
I think it's enough to define one base class for `Result`, `Failure`, `Success` and `Skip`. For example,

```python
def _user_notification(self, context: Context) -> Marker:
    ...
```

**Comment by proofit404** [comment]
Should we follow the same unified interface as ruby does: `__init__` and `__call__`? I like it!

This need additional details. I have no idea about the problem here.

**Comment by sobolevn** [comment]
All ruby `dry` objects and hanami entities seem to have only two methods: `__init__` and `__call__`. All other methods are marked as `private`. That's the idea behind my question. Currently we have things like `.run()`, etc.

**Comment by proofit404** [comment]
Hmm

This is questionable to me. `run` allows much more convenient failure handling. Basically, I use it all the time.

Also, I'm thinking about another `bind` method.

```python
bound = Action().do.bind(
   on_result=...,
   on_permission_failure=...,
   on_invalid_input_failure=...,
)
bound()
```

**Comment by proofit404** [comment]
We will keep API consistent and stick to the `I` expressions for now.
